"""create remaining domain tables

Revision ID: 3a33cfecc22e
Revises: 20260624_0002
Create Date: 2026-06-24 23:06:51.594222
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3a33cfecc22e'
down_revision: str | None = '20260624_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("actor_type IN ('user', 'system', 'integration')", name=op.f('ck_audit_logs_actor_type_valid')),
    sa.CheckConstraint("outcome IN ('success', 'failure')", name=op.f('ck_audit_logs_outcome_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_created_at', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_deleted_at', 'audit_logs', ['deleted_at'], unique=False)
    op.create_index('ix_audit_logs_resource_created_at', 'audit_logs', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_table('analyses',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('system_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("analysis_type IN ('rca', 'log', 'metric', 'anomaly', 'remediation', 'manual')", name=op.f('ck_analyses_analysis_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_analyses_status_valid')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_analyses_confidence_score_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_analyses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_analyses_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_analyses_system_id_systems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index('ix_analyses_deleted_at', 'analyses', ['deleted_at'], unique=False)
    op.create_index('ix_analyses_incident_created_at', 'analyses', ['incident_id', 'created_at'], unique=False)
    op.create_index('ix_analyses_status', 'analyses', ['status'], unique=False)
    op.create_index('ix_analyses_system_created_at', 'analyses', ['system_id', 'created_at'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('system_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('time_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('step_seconds', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('samples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('prometheus', 'cloudwatch', 'custom')", name=op.f('ck_metrics_snapshots_source_valid')),
    sa.CheckConstraint('step_seconds IS NULL OR step_seconds > 0', name=op.f('ck_metrics_snapshots_step_seconds_positive')),
    sa.CheckConstraint('time_range_end >= time_range_start', name=op.f('ck_metrics_snapshots_time_range_valid')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_metrics_snapshots_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_metrics_snapshots_system_id_systems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_snapshots'))
    )
    op.create_index('ix_metrics_snapshots_deleted_at', 'metrics_snapshots', ['deleted_at'], unique=False)
    op.create_index('ix_metrics_snapshots_incident_created_at', 'metrics_snapshots', ['incident_id', 'created_at'], unique=False)
    op.create_index('ix_metrics_snapshots_source', 'metrics_snapshots', ['source'], unique=False)
    op.create_index('ix_metrics_snapshots_system_created_at', 'metrics_snapshots', ['system_id', 'created_at'], unique=False)
    op.create_table('remediation_actions',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('system_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("action_type IN ('kubernetes', 'jenkins', 'aws', 'script', 'manual', 'notification')", name=op.f('ck_remediation_actions_action_type_valid')),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_remediation_actions_risk_level_valid')),
    sa.CheckConstraint("status IN ('pending_approval', 'approved', 'running', 'succeeded', 'failed', 'cancelled', 'rejected')", name=op.f('ck_remediation_actions_status_valid')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_remediation_actions_analysis_id_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_remediation_actions_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_remediation_actions_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_remediation_actions_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], name=op.f('fk_remediation_actions_system_id_systems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_actions'))
    )
    op.create_index('ix_remediation_actions_analysis_id', 'remediation_actions', ['analysis_id'], unique=False)
    op.create_index('ix_remediation_actions_deleted_at', 'remediation_actions', ['deleted_at'], unique=False)
    op.create_index('ix_remediation_actions_incident_status', 'remediation_actions', ['incident_id', 'status'], unique=False)
    op.create_index('ix_remediation_actions_requested_by_id', 'remediation_actions', ['requested_by_id'], unique=False)
    op.create_index('ix_remediation_actions_system_id', 'remediation_actions', ['system_id'], unique=False)
    op.drop_constraint(op.f('uq_permissions_key'), 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.drop_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=False)
    op.create_unique_constraint(op.f('uq_permissions_key'), 'permissions', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_remediation_actions_system_id', table_name='remediation_actions')
    op.drop_index('ix_remediation_actions_requested_by_id', table_name='remediation_actions')
    op.drop_index('ix_remediation_actions_incident_status', table_name='remediation_actions')
    op.drop_index('ix_remediation_actions_deleted_at', table_name='remediation_actions')
    op.drop_index('ix_remediation_actions_analysis_id', table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_index('ix_metrics_snapshots_system_created_at', table_name='metrics_snapshots')
    op.drop_index('ix_metrics_snapshots_source', table_name='metrics_snapshots')
    op.drop_index('ix_metrics_snapshots_incident_created_at', table_name='metrics_snapshots')
    op.drop_index('ix_metrics_snapshots_deleted_at', table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_index('ix_analyses_system_created_at', table_name='analyses')
    op.drop_index('ix_analyses_status', table_name='analyses')
    op.drop_index('ix_analyses_incident_created_at', table_name='analyses')
    op.drop_index('ix_analyses_deleted_at', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_audit_logs_resource_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_deleted_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
